/**
 * Agent Briefing Generator
 *
 * Generates `.gitmem/agent-briefing.md` at session close with a
 * compact summary of memory state. Designed for inclusion in
 * MEMORY.md to bridge PMEM <-> GitMem.
 */

import * as fs from "fs";
import * as path from "path";
import { getGitmemDir } from "./gitmem-dir.js";
import { getStorage } from "./storage.js";

/**
 * Generate and write agent-briefing.md to .gitmem/
 */
export async function writeAgentBriefing(
  newLearnings: number,
  newDecisions: number,
): Promise<void> {
  try {
    const gitmemDir = getGitmemDir();
    if (!gitmemDir || !fs.existsSync(gitmemDir)) return;

    const storage = getStorage();
    const sessions = await storage.query<Record<string, unknown>>("sessions");
    const learnings = await storage.query<Record<string, unknown>>("learnings");
    const threads = await storage.query<Record<string, unknown>>("threads");

    // Count by severity
    const severityCounts: Record<string, number> = {};
    const domainCounts: Record<string, number> = {};
    for (const l of learnings) {
      const sev = l.severity as string || "medium";
      severityCounts[sev] = (severityCounts[sev] || 0) + 1;

      const domains = l.domain as string[] || [];
      for (const d of domains) {
        domainCounts[d] = (domainCounts[d] || 0) + 1;
      }
    }

    // Active threads
    const activeThreads = threads.filter((t) => t.status === "open").length;

    // Top domains (top 5)
    const topDomains = Object.entries(domainCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([d]) => d);

    // Severity breakdown
    const sevParts: string[] = [];
    if (severityCounts.critical) sevParts.push(`${severityCounts.critical} critical`);
    if (severityCounts.high) sevParts.push(`${severityCounts.high} high`);
    if (severityCounts.medium) sevParts.push(`${severityCounts.medium} medium`);
    if (severityCounts.low) sevParts.push(`${severityCounts.low} low`);

    // Recent activity
    const recentParts: string[] = [];
    if (newLearnings > 0) recentParts.push(`+${newLearnings} scars`);
    if (newDecisions > 0) recentParts.push(`+${newDecisions} decisions`);

    const today = new Date().toISOString().split("T")[0];

    const lines: string[] = [
      "<!-- Generated by GitMem at session close. Include in MEMORY.md for cross-session context. -->",
      "## GitMem Status",
      `- **Sessions:** ${sessions.length} total, last: ${today}`,
      `- **Active threads:** ${activeThreads}`,
      `- **Scars earned:** ${learnings.length}${sevParts.length > 0 ? ` (${sevParts.join(", ")})` : ""}`,
    ];

    if (recentParts.length > 0) {
      lines.push(`- **Recent:** ${recentParts.join(", ")} this session`);
    }

    if (topDomains.length > 0) {
      lines.push(`- **Top domains:** ${topDomains.join(", ")}`);
    }

    const briefingPath = path.join(gitmemDir, "agent-briefing.md");
    fs.writeFileSync(briefingPath, lines.join("\n") + "\n");
    console.error(`[agent-briefing] Written to ${briefingPath}`);
  } catch (error) {
    // Non-fatal — don't break session close
    console.warn("[agent-briefing] Failed to write:", error);
  }
}
